on:
  pull_request:
    types: [opened, reopened, synchronize]

name: Build

env:
  DOCS_ARTIFACT_TEMPLATE: dxfeed-net-api-%VERSION%-docs
  RELEASE_PREFIX: "dxFeed .Net API "
  C_API_REPO: "https://github.com/dxfeed/dxfeed-c-api.git"
  BUILD_VERSION: 0.0.0-pr

jobs:

# --------------------------- BUILD DOCUMENTATION
  build_docs:
    runs-on: ubuntu-latest
    name: build documentation
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: |
          echo RELEASE_VERSION=${BUILD_VERSION} >> $GITHUB_ENV
          echo ARTIFACT=$(echo ${DOCS_ARTIFACT_TEMPLATE} | sed "s/%VERSION%/${BUILD_VERSION}/g") >> $GITHUB_ENV
      - name: Check env
        run: |
          echo Artifact: ${{ env.ARTIFACT }}
          echo Release : ${{ env.RELEASE_VERSION }}
      - name: Build documentation
        uses: ./.github/actions/doxygen
        id: build-docs
        with:
          artifact: ${{ env.ARTIFACT }}
          release: ${{ env.RELEASE_VERSION }}
